POST http://localhost:7071/api/links

{
  "links":[
    {
      "id":"https://google.com",
      "url":"https://google.com",
      "title":"Google",
      "description":"Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.",
      "image":""
    },
    {
      "id":"https://github.com",
      "url":"https://github.com",
      "title":"GitHub",
      "description":"GitHub is where over 65 million developers shape the future of software, together. Contribute to the open source community, manage your Git repositories, review code like a pro, track bugs and features, power your CI/CD and DevOps workflows, and secure code before you commit it.",
      "image":""
    },
    {
      "id":"https://stackoverflow.com",
      "url":"https://stackoverflow.com",
      "title":"Stack Overflow",
      "description":"Stack Overflow is the largest, most trusted online community for developers to learn, share their programming knowledge, and build their careers.",
      "image":""
    },
    {
      "id":"https://docs.microsoft.com",
      "url":"https://docs.microsoft.com",
      "title":"Microsoft Docs",
      "description":"Learn how to build and manage powerful applications using Microsoft Azure cloud services. Get documentation, example code, tutorials, and more.",
      "image":""
    }
  ],
  "vanityUrl":"test",
  "description":"",
  "userId":""
}